name: myoconverter
channels:
  - opensim-org
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - absl-py==2.1.0
  - certifi==2024.7.4
  - charset-normalizer==3.3.2
  - colorama==0.4.6
  - contourpy==1.2.1
  - cycler==0.12.1
  - defusedxml==0.7.1
  - fonttools==4.53.1
  - fpdf2==2.7.9
  - glfw
  - idna==3.7
  - importlib-resources==6.4.0
  - joblib==1.4.2
  - kiwisolver==1.4.5
  - loguru==0.7.2
  - lxml==4.9.4
  - matplotlib==3.9.1
  - mujoco==2.3.7
  - networkx==3.2.1
  - numpy==1.23.5
  - packaging==24.1
  - pandas==2.2.2
  - pillow==10.4.0
  - platformdirs==4.2.2
  - pooch==1.8.2
  - pyopengl
  - pyparsing==3.1.2
  - python-dateutil==2.9.0.post0
  - pytz==2024.1
  - pyvista==0.43.5
  - requests==2.32.3
  - scikit-learn==1.5.1
  - scipy==1.13.1
  - scooby==0.10.0
  - seaborn==0.12.2
  - six==1.16.0
  - threadpoolctl==3.5.0
  - trimesh==3.23.5
  - tzdata
  - urllib3==2.2.2
  - vtk==9.3.1
  - zipp==3.19.2
