name: myoconverter
channels:
  - opensim-org
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - mujoco=2.3.7
  - loguru=0.7.2
  - lxml=4.9.4
  - numpy=1.23.5
  - scipy=1.13.0
  - scikit-learn=1.4.2
  - opensim=4.4.1
  - matplotlib=3.8.4
  - trimesh=3.23.5
  - pyvista=0.43.5
  - networkx=3.2.1
  - fpdf2=2.7.8
  - seaborn=0.12.2
