name: myoconverter
channels:
  - opensim-org
  - anaconda
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
  - python=3.9.16
  - mujoco-python=2.3.3
  - loguru=0.5.3
  - lxml=4.9.1
  - numpy=1.21.5
  - scipy=1.10.0
  - scikit-learn=1.2.0
  - opensim=4.4
  - matplotlib=3.6.2
  - trimesh=3.22.2
  - pyvista=0.39.1
  - networkx=2.8.4
  - fpdf2=2.7.4
=======
  - python=3.10
  - mujoco=2.3.7
  - loguru=0.7.0
  - lxml=4.9.3
  - numpy=1.21.6
  - scipy=1.11.2
  - scikit-learn=1.3.0
  - opensim=4.4.1
  - matplotlib=3.7.2
  - trimesh=3.23.5
  - pyvista=0.41.1
  - networkx=3.1
  - fpdf2=2.7.5
>>>>>>> a1c0c5c (Correct conda yaml file for Colab)
  - seaborn=0.12.2
