name: myoconverter
channels:
  - anaconda
  - defaults
  - conda-forge
  - opensim-org
dependencies:
  - fpdf2=2.7.9
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mujoco=2.3.7
  - numpy=1.23.5
  - pandas=2.2.2
  - pyqt=5.15.10
  - python=3.11
  - qt-main=5.15
  - opensim=>4.0
  - lxml
  - loguru
  - scikit-learn
  - seaborn
  - trimesh
  - pyvista
