name: myoconverter
channels:
  - opensim-org
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mujoco=2.3.7
  - loguru=0.7.0
  - lxml=4.9.3
  - numpy=1.21.6
  - scipy=1.11.2
  - scikit-learn=1.3.0
  - opensim=4.4.1
  - matplotlib=3.7.2
  - trimesh=3.23.5
  - pyvista=0.41.1
  - networkx=3.1
  - fpdf2=2.7.5
  - seaborn=0.12.2
