name: myoconverter
channels:
  - opensim-org
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.9,<3.11
  - mujoco=2.3.6
  - loguru=0.7.0
  - lxml=4.9.2
  - numpy=1.21.6
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - opensim=4.4
  - matplotlib=3.7.1
  - trimesh=3.22.3
  - pyvista=0.40.0
  - networkx=3.1
  - fpdf2=2.7.4
  - seaborn=0.12.2
